spring:
  application:
    name: order-item-service-api
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:ORDER-ITEM-SERVICE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
server:
  servlet:
    context-path: /orderitem
  port: 8763
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/